version: '3.8'

services:
  django:
    build: 
      context: ./
      dockerfile: Dockerfile.prod
    container_name: django_bookstore
    # command: python manage.py runserver 0.0.0.0:8000

    # use command after config nginx
    command: gunicorn bookstore.wsgi:application --bind 0.0.0.0:8000

    # command: gunicorn bookstore.wsgi:application -c gunicorn.conf.py

    # เอาไว้ลิ้งค์กับระหว่าง local กับ Sever
    # use command for Check Path local and Sever "docker  inspect django_bookstore"
    volumes:
      - static_volume:/django-app/static
      - media_volume:/django-app/media

    # restart: always

    ports:
      # - 8000:8000

    # use command after config nginx
      - 8000
    env_file:
      - ./.env
    depends_on: 
      - pgdb
  pgdb:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres_data:/django-app/pgdb
    environment:
      # - TZ=Asia/Singapore
      # - PGTZ=Asia/Singapore
      - POSTGRES_USER=admin@gmail.com
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=bookstore
  
  pg4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - 8080:80
    depends_on: 
      - pgdb
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    networks:
      - pgsite

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - static_volume:/django-app/static
      - media_volume:/django-app/media
    restart: always
    ports:
      - 80:80
    depends_on:
      - django

networks:
  pgsite:

volumes:
  postgres_data:
  static_volume:
  media_volume:

